set serveroutput on;

drop table airport_names;
create table airport_names(
  id number(10, 0) primary key,
  name varchar(100) not null
);
/

drop table city_names;
create table city_names (
    id number(10, 0) primary key,
    name varchar(100) not null
);

insert into airport_names values(1,   'Singapore Changi');
insert into airport_names values(2,   'Tokyo Intl Haneda');
insert into airport_names values(3,   'Incheon Intl Airport');
insert into airport_names values(4,   'Munich Airport');
insert into airport_names values(5,   'Hong Kong Intl Airport');
insert into airport_names values(6,   'Hamad Intl Airport');
insert into airport_names values(7,   'Centrair Nagoya');
insert into airport_names values(8,   'Zurich Airport');
insert into airport_names values(9,   'Heathrow Airport');
insert into airport_names values(10,  'Frankfurt Airport');
insert into airport_names values(11,  'Amsterdam Schiphol');
insert into airport_names values(12,  'Kansai Intl Airport');
insert into airport_names values(13,  'Vancouver Airport');
insert into airport_names values(14,  'Narita Airport');
insert into airport_names values(15,  'Copenhagen Airport');
insert into airport_names values(16,  'Brisbane Airport');
insert into airport_names values(17,  'Helsinki Airport');
insert into airport_names values(18,  'Shanghai Hongqiao');
insert into airport_names values(19,  'Cape Town Airport');
insert into airport_names values(20,  'Dubai Airport');
insert into airport_names values(21,  'Taiwan Taoyuan Airport');
insert into airport_names values(22,  'Auckland Airport');
insert into airport_names values(23,  'Sydney Airport');
insert into airport_names values(24,  'Vienna Airport');
insert into airport_names values(25,  'Beijing Capital Airport');
insert into airport_names values(26,  'Cincinnati/Kentucky');
insert into airport_names values(27,  'Hamburg Airport');
insert into airport_names values(28,  'Denver Airport');
insert into airport_names values(29,  'Cologne / Bonn Airport');
insert into airport_names values(30,  'Melbourne Airport');
insert into airport_names values(31,  'Madrid-Barajas Airport');
insert into airport_names values(32,  'Paris Cdg Airport');
insert into airport_names values(33,  'Barcelona Airport');
insert into airport_names values(34,  'Kuala Lumpur Airport');
insert into airport_names values(35,  'King Shaka Airport');
insert into airport_names values(36,  'London City Airport');
insert into airport_names values(37,  'Johannesburg');
insert into airport_names values(38,  'Bangkok Suvarnabhumi');
insert into airport_names values(39,  'San Francisco Airport');
insert into airport_names values(40,  'Dusseldorf Airport');
insert into airport_names values(41,  'Hartsfield-Jackson');
insert into airport_names values(42,  'Bogota Airport');
insert into airport_names values(43,  'Toronto Pearson Airport');
insert into airport_names values(44,  'Soekarno-Hatta Airport');
insert into airport_names values(45,  'Xi''an Airport');
insert into airport_names values(46,  'Dallas/Fort Worth');
insert into airport_names values(47,  'Gimpo Airport');
insert into airport_names values(48,  'Haikou Meilan Airport');
insert into airport_names values(49,  'Abu Dhabi Airport');
insert into airport_names values(50,  'Gold Coast Airport');
insert into airport_names values(51,  'Gatwick Airport');
insert into airport_names values(52,  'Quito Airport');
insert into airport_names values(53,  'Athens Airport');
insert into airport_names values(54,  'Houston IAH');
insert into airport_names values(55,  'Lima Airport');
insert into airport_names values(56,  'Chengdu Airport');
insert into airport_names values(57,  'Bahrain Airport');
insert into airport_names values(58,  'Seattle-Tacoma Airport');
insert into airport_names values(59,  'Oslo Airport');
insert into airport_names values(60,  'Delhi Airport');
insert into airport_names values(61,  'Christchurch Airport');
insert into airport_names values(62,  'Stockholm Arlanda');
insert into airport_names values(63,  'New York JFK Airport');
insert into airport_names values(64,  'Mumbai Airport');
insert into airport_names values(65,  'Halifax Stanfield Airport');
insert into airport_names values(66,  'Guayaquil Airport');
insert into airport_names values(67,  'Bengaluru Airport');
insert into airport_names values(68,  'Lisbon Airport');
insert into airport_names values(69,  'Hyderabad Airport');
insert into airport_names values(70,  'Baku Airport');
insert into airport_names values(71,  'Perth Airport');
insert into airport_names values(72,  'Minneapolis-St Paul');
insert into airport_names values(73,  'Adelaide Airport');
insert into airport_names values(74,  'Moscow Domodedovo');
insert into airport_names values(75,  'Porto Airport');
insert into airport_names values(76,  'Shenzhen Airport');
insert into airport_names values(77,  'Dublin Airport');
insert into airport_names values(78,  'Sanya Airport');
insert into airport_names values(79,  'Malta Airport');
insert into airport_names values(80,  'Montr');
insert into airport_names values(81,  'Moscow Sheremetyevo');
insert into airport_names values(82,  'Billund Airport');
insert into airport_names values(83,  'Hanoi Noi Bai Airport');
insert into airport_names values(84,  'Budapest Airport');
insert into airport_names values(85,  'Birmingham Airport');
insert into airport_names values(86,  'Los Angeles Airport');
insert into airport_names values(87,  'Guangzhou Airport');
insert into airport_names values(88,  'Phoenix Airport');
insert into airport_names values(89,  'Boston Logan Airport');
insert into airport_names values(90,  'Panama Tocumen');
insert into airport_names values(91,  'Brussels Airport');
insert into airport_names values(92,  'Nice Airport');
insert into airport_names values(93,  'Medina Airport');
insert into airport_names values(94,  'Detroit Metropolitan');
insert into airport_names values(95,  'Raleigh-Durham');
insert into airport_names values(96,  'Prague Airport');
insert into airport_names values(97,  'Keflavik Airport');
insert into airport_names values(98,  'Kazan Airport');
insert into airport_names values(99,  'Warsaw Airport');
insert into airport_names values(100, 'Shanghai Pudong');

insert into city_names values(1, '´??Tokyo');
insert into city_names values(2, 'Delhi');
insert into city_names values(3, 'Shanghai');
insert into city_names values(4, 'S?úo Paulo');
insert into city_names values(5, 'Mumbai (Bombay)');
insert into city_names values(6, 'Ciudad de M?êxico (Mexico City)');
insert into city_names values(7, 'Beijing');
insert into city_names values(8, 'Kinki M.M.A. (Osaka)');
insert into city_names values(9, 'Al-Qahirah (Cairo)');
insert into city_names values(10, 'New York-Newark');
insert into city_names values(11, 'Dhaka');
insert into city_names values(12, 'Karachi');
insert into city_names values(13, 'Buenos Aires');
insert into city_names values(14, 'Kolkata (Calcutta)');
insert into city_names values(15, 'Istanbul');
insert into city_names values(16, 'Chongqing');
insert into city_names values(17, 'Lagos');
insert into city_names values(18, 'Manila');
insert into city_names values(19, 'Rio de Janeiro');
insert into city_names values(20, 'Guangzhou, Guangdong');
insert into city_names values(21, 'Los Angeles-Long Beach-Santa Ana');
insert into city_names values(22, 'Moskva (Moscow)');
insert into city_names values(23, 'Kinshasa');
insert into city_names values(24, 'Tianjin');
insert into city_names values(25, 'Paris');
insert into city_names values(26, 'Shenzhen');
insert into city_names values(27, 'Jakarta');
insert into city_names values(28, 'London');
insert into city_names values(29, 'Bangalore');
insert into city_names values(30, 'Lima');
insert into city_names values(31, 'Chennai (Madras)');
insert into city_names values(32, 'Seoul');
insert into city_names values(33, 'Bogot?í');
insert into city_names values(34, 'Chukyo M.M.A. (Nagoya)');
insert into city_names values(35, 'Johannesburg');
insert into city_names values(36, 'Krung Thep (Bangkok)');
insert into city_names values(37, 'Hyderabad');
insert into city_names values(38, 'Chicago');
insert into city_names values(39, 'Lahore');
insert into city_names values(40, 'Tehran');
insert into city_names values(41, 'Wuhan');
insert into city_names values(42, 'Chengdu');
insert into city_names values(43, 'Dongguan');
insert into city_names values(44, 'Nanjing, Jiangsu');
insert into city_names values(45, 'Ahmadabad');
insert into city_names values(46, 'Hong Kong');
insert into city_names values(47, 'Th?ánh Pho Ho Ch?º Minh (Ho Chi Minh City)');
insert into city_names values(48, 'Foshan');
insert into city_names values(49, 'Kuala Lumpur');
insert into city_names values(50, 'Baghdad');
insert into city_names values(51, 'Santiago');
insert into city_names values(52, 'Hangzhou');
insert into city_names values(53, 'Ar-Riyadh (Riyadh)');
insert into city_names values(54, 'Shenyang');
insert into city_names values(55, 'Madrid');
insert into city_names values(56, 'Xian, Shaanxi');
insert into city_names values(57, 'Toronto');
insert into city_names values(58, 'Miami');
insert into city_names values(59, 'Pune (Poona)');
insert into city_names values(60, 'Belo Horizonte');
insert into city_names values(61, 'Dallas-Fort Worth');
insert into city_names values(62, 'Surat');
insert into city_names values(63, 'Houston');
insert into city_names values(64, 'Singapore');
insert into city_names values(65, 'Philadelphia');
insert into city_names values(66, 'Kitakyushu-Fukuoka M.M.A.');
insert into city_names values(67, 'Luanda');
insert into city_names values(68, 'Suzhou, Jiangsu');
insert into city_names values(69, 'Haerbin');
insert into city_names values(70, 'Barcelona');
insert into city_names values(71, 'Atlanta');
insert into city_names values(72, 'Al-Khartum (Khartoum)');
insert into city_names values(73, 'Dar es Salaam');
insert into city_names values(74, 'Sankt Peterburg (Saint Petersburg)');
insert into city_names values(75, 'Washington, D.C.');
insert into city_names values(76, 'Abidjan');
insert into city_names values(77, 'Guadalajara');
insert into city_names values(78, 'Yangon');
insert into city_names values(79, 'Al-Iskandariyah (Alexandria)');
insert into city_names values(80, 'Ankara');
insert into city_names values(81, 'Kabul');
insert into city_names values(82, 'Qingdao');
insert into city_names values(83, 'Chittagong');
insert into city_names values(84, 'Monterrey');
insert into city_names values(85, 'Sydney');
insert into city_names values(86, 'Dalian');
insert into city_names values(87, 'Xiamen');
insert into city_names values(88, 'Zhengzhou');
insert into city_names values(89, 'Boston');
insert into city_names values(90, 'Melbourne');
insert into city_names values(91, 'Bras?ºlia');
insert into city_names values(92, 'Jiddah');
insert into city_names values(93, 'Phoenix-Mesa');
insert into city_names values(94, 'Jinan, Shandong');
insert into city_names values(95, 'Montr?êal');
insert into city_names values(96, 'Shantou');
insert into city_names values(97, 'Nairobi');
insert into city_names values(98, 'Medell?ºn');
insert into city_names values(99, 'Fortaleza');
insert into city_names values(100, 'Kunming');
insert into city_names values(101, 'Changchun');
insert into city_names values(102, 'Changsha');
insert into city_names values(103, 'Recife');
insert into city_names values(104, 'Roma (Rome)');
insert into city_names values(105, 'Zhongshan');
insert into city_names values(106, 'Cape Town');
insert into city_names values(107, 'Detroit');
insert into city_names values(108, 'H?á Noi');
insert into city_names values(109, 'Tel Aviv-Yafo (Tel Aviv-Jaffa)');
insert into city_names values(110, 'P??rto Alegre');
insert into city_names values(111, 'Kano');
insert into city_names values(112, 'Salvador');
insert into city_names values(113, 'Faisalabad');
insert into city_names values(114, 'Berlin');
insert into city_names values(115, 'Halab (Aleppo)');
insert into city_names values(116, 'Dakar');
insert into city_names values(117, 'Dar-el-Beida (Casablanca)');
insert into city_names values(118, '??r??mqi (Wulumqi)');
insert into city_names values(119, 'Taiyuan, Shanxi');
insert into city_names values(120, 'Curitiba');
insert into city_names values(121, 'Jaipur');
insert into city_names values(122, 'Shizuoka-Hamamatsu M.M.A.');
insert into city_names values(123, 'Hefei');
insert into city_names values(124, 'San Francisco-Oakland');
insert into city_names values(125, 'Fuzhou, Fujian');
insert into city_names values(126, 'Shijiazhuang');
insert into city_names values(127, 'Seattle');
insert into city_names values(128, 'Addis Ababa');
insert into city_names values(129, 'Nanning');
insert into city_names values(130, 'Lucknow');
insert into city_names values(131, 'Busan');
insert into city_names values(132, 'Wenzhou');
insert into city_names values(133, 'Ibadan');
insert into city_names values(134, 'Ningbo');
insert into city_names values(135, 'San Diego');
insert into city_names values(136, 'Milano (Milan)');
insert into city_names values(137, 'Yaound?ê');
insert into city_names values(138, 'Ath?ºnai (Athens)');
insert into city_names values(139, 'Wuxi, Jiangsu');
insert into city_names values(140, 'Campinas');
insert into city_names values(141, 'Izmir');
insert into city_names values(142, 'Kanpur');
insert into city_names values(143, 'Mashhad');
insert into city_names values(144, 'Puebla');
insert into city_names values(145, 'Sana''a');
insert into city_names values(146, 'Santo Domingo');
insert into city_names values(147, 'Douala');
insert into city_names values(148, 'Kyiv (Kiev)');
insert into city_names values(149, 'Ciudad de Guatemala (Guatemala City)');
insert into city_names values(150, 'Caracas');
insert into city_names values(151, 'Durban');
insert into city_names values(152, 'Lisboa (Lisbon)');
insert into city_names values(153, 'Guiyang');
insert into city_names values(154, 'Pyongyang');
insert into city_names values(155, 'Surabaya');
insert into city_names values(156, 'Minneapolis-St. Paul');
insert into city_names values(157, 'Al Kuwayt (Kuwait City)');
insert into city_names values(158, 'Tangshan, Hebei');
insert into city_names values(159, 'Ouagadougou');
insert into city_names values(160, 'Lanzhou');
insert into city_names values(161, 'Guayaquil');
insert into city_names values(162, 'Incheon');
insert into city_names values(163, 'Nagpur');
insert into city_names values(164, 'Taipei');
insert into city_names values(165, 'Tampa-St. Petersburg');
insert into city_names values(166, 'Cali');
insert into city_names values(167, 'Manchester');
insert into city_names values(168, 'Antananarivo');
insert into city_names values(169, 'Denver-Aurora');
insert into city_names values(170, 'Kumasi');
insert into city_names values(171, 'El Djaza?»r  (Algiers)');
insert into city_names values(172, 'Changzhou, Jiangsu');
insert into city_names values(173, 'Sapporo');
insert into city_names values(174, 'Dimashq (Damascus)');
insert into city_names values(175, 'Coimbatore');
insert into city_names values(176, 'Bandung');
insert into city_names values(177, 'Nanchang');
insert into city_names values(178, 'Bamako');
insert into city_names values(179, 'Birmingham (West Midlands)');
insert into city_names values(180, 'Rawalpindi');
insert into city_names values(181, 'Vancouver');
insert into city_names values(182, 'Kozhikode (Calicut)');
insert into city_names values(183, 'San Juan');
insert into city_names values(184, 'Indore');
insert into city_names values(185, 'Abuja');
insert into city_names values(186, 'Port-au-Prince');
insert into city_names values(187, 'Zibo');
insert into city_names values(188, 'Kochi (Cochin)');
insert into city_names values(189, 'Dubayy (Dubai)');
insert into city_names values(190, 'Baku');
insert into city_names values(191, 'Asunci??n');
insert into city_names values(192, 'Port Harcourt');
insert into city_names values(193, 'Thrissur');
insert into city_names values(194, 'Huizhou');
insert into city_names values(195, 'Goi?ónia');
insert into city_names values(196, 'Accra');
insert into city_names values(197, 'Las Vegas');
insert into city_names values(198, 'Baltimore');
insert into city_names values(199, 'Tashkent');
insert into city_names values(200, 'Daegu');
insert into city_names values(201, 'Bayrut (Beirut)');
insert into city_names values(202, 'Malappuram');
insert into city_names values(203, 'Patna');
insert into city_names values(204, 'Medan');
insert into city_names values(205, 'Brisbane');
insert into city_names values(206, 'Napoli (Naples)');
insert into city_names values(207, 'Maracaibo');
insert into city_names values(208, 'Weifang');
insert into city_names values(209, 'Riverside-San Bernardino');
insert into city_names values(210, 'St. Louis');
insert into city_names values(211, 'Bel?êm');
insert into city_names values(212, 'Lusaka');
insert into city_names values(213, 'Hiroshima');
insert into city_names values(214, 'Toluca de Lerdo');
insert into city_names values(215, 'Kannur');
insert into city_names values(216, 'Muqdisho (Mogadishu)');
insert into city_names values(217, 'La Habana (Havana)');
insert into city_names values(218, 'Gujranwala');
insert into city_names values(219, 'Yantai');
insert into city_names values(220, 'Santa Cruz');
insert into city_names values(221, 'Bhopal');
insert into city_names values(222, 'Sendai');
insert into city_names values(223, 'Shaoxing');
insert into city_names values(224, 'Pretoria');
insert into city_names values(225, 'Bruxelles-Brussel');
insert into city_names values(226, 'San Antonio');
insert into city_names values(227, 'Manaus');
insert into city_names values(228, 'Lubumbashi');
insert into city_names values(229, 'Luoyang');
insert into city_names values(230, 'Mbuji-Mayi');
insert into city_names values(231, 'Portland');
insert into city_names values(232, 'Huaian');
insert into city_names values(233, 'Tunis');
insert into city_names values(234, 'Barranquilla');
insert into city_names values(235, 'Tijuana');
insert into city_names values(236, 'Nantong');
insert into city_names values(237, 'Vadodara');
insert into city_names values(238, 'Rabat');
insert into city_names values(239, 'Agra');
insert into city_names values(240, 'Thiruvananthapuram');
insert into city_names values(241, 'Baotou');
insert into city_names values(242, 'Conakry');
insert into city_names values(243, 'Kampala');
insert into city_names values(244, 'Visakhapatnam');
insert into city_names values(245, 'Bursa');
insert into city_names values(246, 'Multan');
insert into city_names values(247, 'Sacramento');
insert into city_names values(248, 'Xuzhou');
insert into city_names values(249, 'Minsk');
insert into city_names values(250, 'West Yorkshire');
insert into city_names values(251, 'Haikou');
insert into city_names values(252, 'Brazzaville');
insert into city_names values(253, 'Esfahan');
insert into city_names values(254, 'Bucuresti (Bucharest)');
insert into city_names values(255, 'Perth');
insert into city_names values(256, 'Hamburg');
insert into city_names values(257, 'Adana');
insert into city_names values(258, 'La Paz');
insert into city_names values(259, 'Samut Prakan');
insert into city_names values(260, 'Karaj');
insert into city_names values(261, 'Le??n de los Aldamas');
insert into city_names values(262, 'Hohhot');
insert into city_names values(263, 'Nashik');
insert into city_names values(264, 'Cleveland');
insert into city_names values(265, 'Hyderabad');
insert into city_names values(266, 'Makkah (Mecca)');
insert into city_names values(267, 'Yangzhou');
insert into city_names values(268, 'Torino (Turin)');
insert into city_names values(269, 'Vijayawada');
insert into city_names values(270, 'Wien (Vienna)');
insert into city_names values(271, 'Peshawar');
insert into city_names values(272, 'Valencia');
insert into city_names values(273, 'Phnum P?ênh (Phnom Penh)');
insert into city_names values(274, 'Orlando');
insert into city_names values(275, 'San Jose');
insert into city_names values(276, 'Quito');
insert into city_names values(277, 'Warszawa (Warsaw)');
insert into city_names values(278, 'Pittsburgh');
insert into city_names values(279, 'Ludhiana');
insert into city_names values(280, 'Budapest');
insert into city_names values(281, 'Montevideo');
insert into city_names values(282, 'Linyi, Shandong');
insert into city_names values(283, 'Al-Mawsil (Mosul)');
insert into city_names values(284, 'Cincinnati');
insert into city_names values(285, 'Austin');
insert into city_names values(286, 'Ciudad de Panam?í (Panama City)');
insert into city_names values(287, 'Shiraz');
insert into city_names values(288, 'Taizhou, Zhejiang');
insert into city_names values(289, 'Indianapolis');
insert into city_names values(290, 'Hims (Homs)');
insert into city_names values(291, 'Grande Vit??ria');
insert into city_names values(292, 'Handan');
insert into city_names values(293, 'Semarang');
insert into city_names values(294, 'Davao City');
insert into city_names values(295, 'Daqing');
insert into city_names values(296, 'Liuzhou');
insert into city_names values(297, 'Charlotte');
insert into city_names values(298, 'Lyon');
insert into city_names values(299, 'Marseille-Aix-en-Provence');
insert into city_names values(300, 'Kansas City');
insert into city_names values(301, 'Rajkot');
insert into city_names values(302, 'Yinchuan');
insert into city_names values(303, 'Madurai');
insert into city_names values(304, 'Jiangmen');
insert into city_names values(305, 'Tabriz');
insert into city_names values(306, 'Daejon');
insert into city_names values(307, 'Anshan');
insert into city_names values(308, 'Meerut');
insert into city_names values(309, 'Zhuhai');
insert into city_names values(310, 'Varanasi (Benares)');
insert into city_names values(311, 'Baixada Santista');
insert into city_names values(312, 'Gwangju');
insert into city_names values(313, 'Xiangyang');
insert into city_names values(314, 'Datong');
insert into city_names values(315, 'Gaziantep');
insert into city_names values(316, 'Kaohsiung');
insert into city_names values(317, 'Almaty');
insert into city_names values(318, 'Jilin');
insert into city_names values(319, 'C??rdoba');
insert into city_names values(320, 'Columbus, Ohio');
insert into city_names values(321, 'Harare');
insert into city_names values(322, 'Novosibirsk');
insert into city_names values(323, 'Benin City');
insert into city_names values(324, 'Makassar (Ujung Pandang)');
insert into city_names values(325, 'Stockholm');
insert into city_names values(326, 'Virginia Beach');
insert into city_names values(327, 'Palembang');
insert into city_names values(328, 'Qiqihaer');
insert into city_names values(329, 'Jamshedpur');
insert into city_names values(330, 'Kharkiv');
insert into city_names values(331, 'M??nchen (Munich)');
insert into city_names values(332, 'Putian');
insert into city_names values(333, 'Grande S?úo Lu?ºs');
insert into city_names values(334, 'Yancheng, Jiangsu');
insert into city_names values(335, 'Srinagar');
insert into city_names values(336, 'Wuhu, Anhui');
insert into city_names values(337, 'Kollam');
insert into city_names values(338, 'Milwaukee');
insert into city_names values(339, 'Quanzhou');
insert into city_names values(340, 'Batam');
insert into city_names values(341, 'Ciudad Ju?írez');
insert into city_names values(342, 'Jining, Shandong');
insert into city_names values(343, 'Rosario');
insert into city_names values(344, 'Yekaterinburg');
insert into city_names values(345, 'Ulaanbaatar');
insert into city_names values(346, 'Raipur');
insert into city_names values(347, 'Islamabad');
insert into city_names values(348, 'Auckland');
insert into city_names values(349, 'Aurangabad');
insert into city_names values(350, 'Calgary');
insert into city_names values(351, 'Jabalpur');
insert into city_names values(352, 'Chaozhou');
insert into city_names values(353, 'Torre??n');
insert into city_names values(354, 'Huainan');
insert into city_names values(355, 'Ottawa-Gatineau');
insert into city_names values(356, 'Xining');
insert into city_names values(357, 'Praha (Prague)');
insert into city_names values(358, 'Asansol');
insert into city_names values(359, 'Cixi');
insert into city_names values(360, 'Hengyang');
insert into city_names values(361, 'Porto');
insert into city_names values(362, 'Fushun, Liaoning');
insert into city_names values(363, 'Allahabad');
insert into city_names values(364, 'Jodhpur');
insert into city_names values(365, 'Al-Madinah (Medina)');
insert into city_names values(366, 'Sharjah');
insert into city_names values(367, 'Edmonton');
insert into city_names values(368, 'Huambo');
insert into city_names values(369, 'K?ªbenhavn (Copenhagen)');
insert into city_names values(370, 'Quer?êtaro');
insert into city_names values(371, 'Macei??');
insert into city_names values(372, 'Amritsar');
insert into city_names values(373, 'Monrovia');
insert into city_names values(374, 'Yichang');
insert into city_names values(375, 'Ranchi');
insert into city_names values(376, 'NDjam?êna');
insert into city_names values(377, 'Kigali');
insert into city_names values(378, 'Adelaide');
insert into city_names values(379, 'Dhanbad');
insert into city_names values(380, 'Z??rich (Zurich)');
insert into city_names values(381, 'Cochabamba');
insert into city_names values(382, 'Hamah');
insert into city_names values(383, 'Tiruppur');
insert into city_names values(384, 'Sofia');
insert into city_names values(385, 'Taichung');
insert into city_names values(386, 'Glasgow');
insert into city_names values(387, 'Gwalior');
insert into city_names values(388, 'Taian, Shandong');
insert into city_names values(389, 'Joinville');
insert into city_names values(390, 'Ahvaz');
insert into city_names values(391, 'Bucaramanga');
insert into city_names values(392, 'Nizhniy Novgorod');
insert into city_names values(393, 'Qom');
insert into city_names values(394, 'Providence');
insert into city_names values(395, 'Konya');
insert into city_names values(396, 'Maputo');
insert into city_names values(397, 'Taizhou, Jiangsu');
insert into city_names values(398, 'Kathmandu');
insert into city_names values(399, 'Beograd (Belgrade)');
insert into city_names values(400, 'Florian??polis');
insert into city_names values(401, 'Helsinki');
insert into city_names values(402, 'Port Elizabeth');
insert into city_names values(403, 'Can Tho');
insert into city_names values(404, 'F?Ês');
insert into city_names values(405, 'Jacksonville, Florida');
insert into city_names values(406, 'San Jos?ê');
insert into city_names values(407, 'Dublin');
insert into city_names values(408, 'Kananga');
insert into city_names values(409, 'Mandalay');
insert into city_names values(410, 'Natal');
insert into city_names values(411, 'Maracay');
insert into city_names values(412, 'Irbil (Erbil)');
insert into city_names values(413, 'Samara');
insert into city_names values(414, 'Kota');
insert into city_names values(415, 'Kazan');
insert into city_names values(416, 'Omsk');
insert into city_names values(417, 'Chelyabinsk');
insert into city_names values(418, 'Vereeniging');
insert into city_names values(419, 'Amman');
insert into city_names values(420, 'Zhanjiang');
insert into city_names values(421, 'Tbilisi');
insert into city_names values(422, 'San Luis Potos?º');
insert into city_names values(423, 'Abu Zaby (Abu Dhabi)');
insert into city_names values(424, 'Anyang');
insert into city_names values(425, 'Raleigh');
insert into city_names values(426, 'Chandigarh');
insert into city_names values(427, 'Marrakech');
insert into city_names values(428, 'Durg-Bhilainagar');
insert into city_names values(429, 'Tarabulus (Tripoli)');
insert into city_names values(430, 'Tegucigalpa');
insert into city_names values(431, 'Pekan Baru');
insert into city_names values(432, 'Bareilly');
insert into city_names values(433, 'Onitsha');
insert into city_names values(434, 'Qinhuangdao');
insert into city_names values(435, 'Quetta');
insert into city_names values(436, 'Denpasar');
insert into city_names values(437, 'Memphis');
insert into city_names values(438, 'Tiruchirappalli');
insert into city_names values(439, 'Baoding');
insert into city_names values(440, 'Nashville-Davidson');
insert into city_names values(441, 'Mombasa');
insert into city_names values(442, 'Lianyungang');
insert into city_names values(443, 'Suweon');
insert into city_names values(444, 'San Salvador');
insert into city_names values(445, 'Hefa (Haifa)');
insert into city_names values(446, 'Rostov-na-Donu (Rostov-on-Don)');
insert into city_names values(447, 'Salt Lake City');
insert into city_names values(448, 'Jo?úo Pessoa');
insert into city_names values(449, 'Cartagena');
insert into city_names values(450, 'Amsterdam');
insert into city_names values(451, 'Niamey');
insert into city_names values(452, 'Zhuzhou');
insert into city_names values(453, 'Mysore');
insert into city_names values(454, 'Yiwu');
insert into city_names values(455, 'Bogor');
insert into city_names values(456, 'Hai Ph??ng');
insert into city_names values(457, 'Antalya');
insert into city_names values(458, 'Benxi');
insert into city_names values(459, 'Ufa');
insert into city_names values(460, 'M?êrida');
insert into city_names values(461, 'Mianyang, Sichuan');
insert into city_names values(462, 'Ad-Dammam');
insert into city_names values(463, 'Rizhao');
insert into city_names values(464, 'Zhenjiang, Jiangsu');
insert into city_names values(465, 'Suqian');
insert into city_names values(466, 'Nanchong');
insert into city_names values(467, 'Kaduna');
insert into city_names values(468, 'Yongin');
insert into city_names values(469, 'Yerevan');
insert into city_names values(470, 'Guwahati (Gauhati)');
insert into city_names values(471, 'Guilin');
insert into city_names values(472, 'Kisangani');
insert into city_names values(473, 'Changwon');
insert into city_names values(474, 'Barquisimeto');
insert into city_names values(475, 'Aligarh');
insert into city_names values(476, 'K?Âln (Cologne)');
insert into city_names values(477, 'Jinzhou');
insert into city_names values(478, 'Mexicali');
insert into city_names values(479, 'Louisville');
insert into city_names values(480, 'Aguascalientes');
insert into city_names values(481, 'Nay Pyi Taw');
insert into city_names values(482, 'Richmond');
insert into city_names values(483, 'Zaozhuang');
insert into city_names values(484, 'Lille');
insert into city_names values(485, 'Yingkou');
insert into city_names values(486, 'Moradabad');
insert into city_names values(487, 'Volgograd');
insert into city_names values(488, 'Khulna');
insert into city_names values(489, 'Hubli-Dharwad');
insert into city_names values(490, 'Al-Basrah (Basra)');
insert into city_names values(491, 'Chifeng');
insert into city_names values(492, 'Nanyang, Henan');
insert into city_names values(493, 'Odesa');
insert into city_names values(494, 'Xiangtan, Hunan');
insert into city_names values(495, 'Mendoza');
insert into city_names values(496, 'Krasnoyarsk');
insert into city_names values(497, 'Freetown');
insert into city_names values(498, 'Puning');
insert into city_names values(499, 'Sulaimaniya');
insert into city_names values(500, 'Salem');
insert into city_names values(501, 'Baoji');
insert into city_names values(502, 'Bhubaneswar');
insert into city_names values(503, 'Vientiane');
insert into city_names values(504, 'Pingdingshan, Henan');
insert into city_names values(505, 'Antwerpen');
insert into city_names values(506, 'Rotterdam');
insert into city_names values(507, 'Cuernavaca');
insert into city_names values(508, 'Xinxiang');
insert into city_names values(509, 'Oslo');
insert into city_names values(510, 'Solapur');
insert into city_names values(511, 'Zhangjiakou');
insert into city_names values(512, 'Perm');
insert into city_names values(513, 'Tanger');
insert into city_names values(514, 'Huaibei');
insert into city_names values(515, 'Ruian');
insert into city_names values(516, 'Jiaxing');
insert into city_names values(517, 'Jinhua');
insert into city_names values(518, 'Pointe-Noire');
insert into city_names values(519, 'Seongnam');
insert into city_names values(520, 'Nouakchott');
insert into city_names values(521, 'Dongying');
insert into city_names values(522, 'Nice-Cannes');
insert into city_names values(523, 'Bandar Lampung');
insert into city_names values(524, 'Jingzhou, Hubei');
insert into city_names values(525, 'Hartford');
insert into city_names values(526, 'Yueyang');
insert into city_names values(527, 'Teresina');
insert into city_names values(528, 'Tengzhou');
insert into city_names values(529, 'Dnipropetrovsk');
insert into city_names values(530, 'Lom?ê');
insert into city_names values(531, 'Managua');
insert into city_names values(532, 'Jalandhar');
insert into city_names values(533, 'Da Nang');
insert into city_names values(534, 'Cebu City');
insert into city_names values(535, 'Aba');
insert into city_names values(536, 'Goyang');
insert into city_names values(537, 'Chihuahua');
insert into city_names values(538, 'Bridgeport-Stamford');
insert into city_names values(539, 'Toulouse');
insert into city_names values(540, 'Matola');
insert into city_names values(541, 'Zamboanga City');
insert into city_names values(542, 'Donetsk');
insert into city_names values(543, 'Saltillo');
insert into city_names values(544, 'Diyarbakir');
insert into city_names values(545, 'Oklahoma City');
insert into city_names values(546, 'Suzhou, Anhui');
insert into city_names values(547, 'New Orleans');
insert into city_names values(548, 'Tampico');
insert into city_names values(549, 'Morelia');
insert into city_names values(550, 'Bahawalpur');
insert into city_names values(551, 'Buffalo');
insert into city_names values(552, 'Tucson');
insert into city_names values(553, 'Johor Bahru');
insert into city_names values(554, 'Voronezh');
insert into city_names values(555, 'San Miguel de Tucum?ín');
insert into city_names values(556, 'Jieyang');
insert into city_names values(557, 'Valpara?ºso');
insert into city_names values(558, 'Lilongwe');
insert into city_names values(559, 'Kayseri');
insert into city_names values(560, 'Ulsan');
insert into city_names values(561, 'Padang');
insert into city_names values(562, 'Acapulco de Ju?írez');
insert into city_names values(563, 'Kermanshah');
insert into city_names values(564, 'Fuyang');
insert into city_names values(565, 'Bordeaux');
insert into city_names values(566, 'Jixi, Heilongjiang');
insert into city_names values(567, 'Najaf');
insert into city_names values(568, 'Southampton/Portsmouth (South Hampshire)');
insert into city_names values(569, 'Adan (Aden)');
insert into city_names values(570, 'Veracruz');
insert into city_names values(571, 'Liuan');
insert into city_names values(572, 'El Paso');
insert into city_names values(573, 'Wenling');
insert into city_names values(574, 'Bucheon');
insert into city_names values(575, 'Liverpool');
insert into city_names values(576, 'Yueqing');
insert into city_names values(577, 'Bishkek');
insert into city_names values(578, 'Samarinda');
insert into city_names values(579, 'McAllen');
insert into city_names values(580, 'Maanshan');
insert into city_names values(581, 'Wahran (Oran)');
insert into city_names values(582, 'Ilorin');
insert into city_names values(583, 'Malang');
insert into city_names values(584, 'Huzhou');
insert into city_names values(585, 'Mersin');
insert into city_names values(586, 'Warangal');
insert into city_names values(587, 'Palermo');
insert into city_names values(588, 'Reynosa');
insert into city_names values(589, 'San Pedro Sula');
insert into city_names values(590, 'C??cuta');
insert into city_names values(591, 'Mudanjiang');
insert into city_names values(592, 'Arequipa');
insert into city_names values(593, 'Saharanpur');
insert into city_names values(594, 'Honolulu');
insert into city_names values(595, 'Uyo');
insert into city_names values(596, 'La Plata');
insert into city_names values(597, 'Weihai');
insert into city_names values(598, 'Canc??n');
insert into city_names values(599, 'Villahermosa');
insert into city_names values(600, 'Rajshahi');
insert into city_names values(601, 'Bengbu');
insert into city_names values(602, 'Campo Grande');
insert into city_names values(603, 'Bergamo');
insert into city_names values(604, 'Jerusalem');
insert into city_names values(605, 'Masqat (Muscat)');
insert into city_names values(606, 'Mwanza');
insert into city_names values(607, 'Bien Hoa');
insert into city_names values(608, 'Bukavu');
insert into city_names values(609, 'Siliguri');
insert into city_names values(610, 'Shiyan');
insert into city_names values(611, 'Albuquerque');
insert into city_names values(612, 'Aracaju');
insert into city_names values(613, 'Dushanbe');
insert into city_names values(614, 'Dandong');
insert into city_names values(615, 'Liuyang');
insert into city_names values(616, 'Concepci??n');
insert into city_names values(617, 'Tainan');
insert into city_names values(618, 'Saratov');
insert into city_names values(619, 'Dehradun');
insert into city_names values(620, 'Leshan');
insert into city_names values(621, 'Pizhou');
insert into city_names values(622, 'Pingxiang, Jiangxi');
insert into city_names values(623, 'Jos');
insert into city_names values(624, 'Valencia');
insert into city_names values(625, 'Liupanshui');
insert into city_names values(626, 'Blantyre-Limbe');
insert into city_names values(627, 'Krasnodar');
insert into city_names values(628, 'Qu?êbec');
insert into city_names values(629, 'Kaifeng');
insert into city_names values(630, 'Hermosillo');
insert into city_names values(631, 'Asmara');
insert into city_names values(632, 'Zunyi');
insert into city_names values(633, 'Ganzhou');
insert into city_names values(634, 'Londrina');
insert into city_names values(635, 'Trujillo');
insert into city_names values(636, 'Birmingham');
insert into city_names values(637, 'Bangui');
insert into city_names values(638, 'Bhiwandi');
insert into city_names values(639, 'Santa Fe');
insert into city_names values(640, 'Newcastle upon Tyne');
insert into city_names values(641, 'Fuxin');
insert into city_names values(642, 'Liaoyang');
insert into city_names values(643, 'Tasikmalaya');
insert into city_names values(644, 'Xintai');
insert into city_names values(645, 'Bologna');
insert into city_names values(646, 'Lattakia');
insert into city_names values(647, 'Omaha');
insert into city_names values(648, 'Tuxtla Gutierrez');
insert into city_names values(649, 'Luzhou');
insert into city_names values(650, 'Ansan');
insert into city_names values(651, 'Soshanguve');
insert into city_names values(652, 'Laiwu');
insert into city_names values(653, 'Luohe');
insert into city_names values(654, 'Nnewi');
insert into city_names values(655, 'Culiac?ín');
insert into city_names values(656, 'Bouake');
insert into city_names values(657, 'Guigang');
insert into city_names values(658, 'Hargeysa');
insert into city_names values(659, 'Krak??w (Cracow)');
insert into city_names values(660, 'Winnipeg');
insert into city_names values(661, 'Astana');
insert into city_names values(662, 'Abomey-Calavi');
insert into city_names values(663, 'Guntur');
insert into city_names values(664, 'Nottingham');
insert into city_names values(665, 'Zaporizhzhya');
insert into city_names values(666, 'Huangshi');
insert into city_names values(667, 'Bujumbura');
insert into city_names values(668, 'Shimkent');
insert into city_names values(669, 'Ashgabat');
insert into city_names values(670, 'Banghazi');
insert into city_names values(671, 'Hamilton');
insert into city_names values(672, 'Hufuf-Mubarraz');
insert into city_names values(673, 'Xingtai');
insert into city_names values(674, 'Shaoguan');
insert into city_names values(675, 'Chenzhou');
insert into city_names values(676, 'Changzhi');
insert into city_names values(677, 'Orumiyeh');
insert into city_names values(678, 'Ipoh');
insert into city_names values(679, 'Thessaloniki');
insert into city_names values(680, 'Al-Raqqa');
insert into city_names values(681, 'Lvov');
insert into city_names values(682, 'Yibin');
insert into city_names values(683, 'Dayton');
insert into city_names values(684, 'Rochester');
insert into city_names values(685, 'Jiaozuo');
insert into city_names values(686, 'Haicheng');
insert into city_names values(687, 'Puducherry');
insert into city_names values(688, 'Xalapa');
insert into city_names values(689, 'Tolyatti');
insert into city_names values(690, 'Maiduguri');
insert into city_names values(691, 'Sorocaba');
insert into city_names values(692, 'Zhangzhou');
insert into city_names values(693, 'Changshu');
insert into city_names values(694, 'Chi?èin?âu');
insert into city_names values(695, 'Tianmen');
insert into city_names values(696, 'Gorakhpur');
insert into city_names values(697, 'Bobo-Dioulasso');
insert into city_names values(698, 'Ad-Dawhah (Doha)');
insert into city_names values(699, 'Zhucheng');
insert into city_names values(700, 'Mekn?Ês');
insert into city_names values(701, 'Owerri');
insert into city_names values(702, 'Sargodha');
insert into city_names values(703, 'Frankfurt am Main');
insert into city_names values(704, 'Safaqis');
insert into city_names values(705, 'Nyala');
insert into city_names values(706, 'Allentown-Bethlehem');
insert into city_names values(707, 'Changde');
insert into city_names values(708, 'Fresno');
insert into city_names values(709, 'Sekondi Takoradi');
insert into city_names values(710, 'Tulsa');
insert into city_names values(711, 'Barcelona-Puerto La Cruz');
insert into city_names values(712, 'Shangqiu');
insert into city_names values(713, 'Rasht');
insert into city_names values(714, 'Libreville');
insert into city_names values(715, 'Colombo');
insert into city_names values(716, 'Ikorodu');
insert into city_names values(717, 'Bikaner');
insert into city_names values(718, 'Sheffield');
insert into city_names values(719, 'Eskisehir');
insert into city_names values(720, 'Huludao');
insert into city_names values(721, '?ü??d??');
insert into city_names values(722, 'Zaria');
insert into city_names values(723, 'Xinyang');
insert into city_names values(724, 'Sevilla');
insert into city_names values(725, 'Florence');
insert into city_names values(726, 'Zaragoza');
insert into city_names values(727, 'Yangquan');
insert into city_names values(728, 'Linfen');
insert into city_names values(729, 'Zigong');
insert into city_names values(730, 'Firozabad');
insert into city_names values(731, 'Ciudad Guayana');
insert into city_names values(732, 'Taizz');
insert into city_names values(733, 'Amravati');
insert into city_names values(734, 'Panjin');
insert into city_names values(735, 'Cheongju');
insert into city_names values(736, 'Binzhou');
insert into city_names values(737, 'Qingyuan');
insert into city_names values(738, 'Genova (Genoa)');
insert into city_names values(739, 'Xinyu');
insert into city_names values(740, 'Cuttack');
insert into city_names values(741, 'Sarasota-Bradenton');
insert into city_names values(742, 'Tshikapa');
insert into city_names values(743, 'Cagayan de Oro City');
insert into city_names values(744, 'Karbala');
insert into city_names values(745, 'Zagreb');
insert into city_names values(746, 'Jiangyin');
insert into city_names values(747, 'Chengde');
insert into city_names values(748, 'Cotonou');
insert into city_names values(749, 'Jiujiang');
insert into city_names values(750, 'Zhuji');
insert into city_names values(751, 'Banjarmasin');
insert into city_names values(752, 'Krivoi Rog');
insert into city_names values(753, 'Enugu');
insert into city_names values(754, 'Xianyang, Shaanxi');
insert into city_names values(755, 'Bazhong');
insert into city_names values(756, 'Liaocheng');
insert into city_names values(757, 'Cape Coral');
insert into city_names values(758, 'Ar-Rayyan');
insert into city_names values(759, 'Jeonju');
insert into city_names values(760, 'Misratah');
insert into city_names values(761, 'Guiping');
insert into city_names values(762, 'Sylhet');
insert into city_names values(763, 'Jammu');
insert into city_names values(764, 'Xiaogan');
insert into city_names values(765, 'Bur Said');
insert into city_names values(766, 'Xinghua');
insert into city_names values(767, 'Jiamusi');
insert into city_names values(768, 'Oaxaca de Ju?írez');
insert into city_names values(769, 'Malegaon');
insert into city_names values(770, 'Panzhihua');
insert into city_names values(771, 'Baton Rouge');
insert into city_names values(772, 'Warri');
insert into city_names values(773, 'Celaya');
insert into city_names values(774, 'Belgaum');
insert into city_names values(775, 'Li?Êge');
insert into city_names values(776, 'Mangalore');
insert into city_names values(777, 'Padova');
insert into city_names values(778, 'Balikpapan');
insert into city_names values(779, 'Ribeir?úo  Preto');
insert into city_names values(780, 'Concord');
insert into city_names values(781, 'Kirkuk');
insert into city_names values(782, 'Nellore');
insert into city_names values(783, 's-Gravenhage (The Hague)');
insert into city_names values(784, 'Nampula');
insert into city_names values(785, 'Oshogbo');
insert into city_names values(786, 'Mar Del Plata');
insert into city_names values(787, 'Yongzhou');
insert into city_names values(788, 'Bristol');
insert into city_names values(789, 'Bhavnagar');
insert into city_names values(790, 'Bulawayo');
insert into city_names values(791, 'Knoxville');
insert into city_names values(792, 'Springfield, Massachusett, Connecticut');
insert into city_names values(793, 'Tianshui');
insert into city_names values(794, 'Yichun, Heilongjiang');
insert into city_names values(795, 'Yichun, Jiangxi');
insert into city_names values(796, 'Makhachkala');
insert into city_names values(797, 'Anqing');
insert into city_names values(798, 'Uberl?óndia');
insert into city_names values(799, 'Taixing');
insert into city_names values(800, 'Baishan');

select * from airport_names;
select * from city_names;